services:
  payflow.api:
    image: ${DOCKER_REGISTRY-}payflowapi
    build:
      context: .
      dockerfile: src/PayFlow.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5001
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PayFlow;User Id=sa;Password=PayFlow@123!;TrustServerCertificate=True;Encrypt=True;MultipleActiveResultSets=True
      - Redis__ConnectionString=redis:6379
    ports:
      - "5000:5000"
      - "5001:5001"
    # depends_on:
    #   sqlserver:
    #     condition: service_healthy
    #   redis:
    #     condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-dev
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - MSSQL_SA_PASSWORD=PayFlow@123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "(/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P \"PayFlow@123!\" -Q \"SELECT 1\") || (/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"PayFlow@123!\" -Q \"SELECT 1\" -C) || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  redis:
    image: redis:7.2-alpine
    container_name: redis-dev
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  sqlserver_data:
  redis_data: